runtime:
  cache_dir: ./.cache/antora
site:
  title: Blog - Yuzu tech
  url: https://blog.yuzutech.fr
  start_page: ROOT::index.adoc
content:
  sources:
  - url: '.'
    branches: HEAD
    start_path: blog
ui:
  bundle:
    url: './ui/bundle'
  supplemental_files: ./ui/supplemental-ui
antora:
  extensions:
    - ./lib/blog-extension.js
asciidoc:
  attributes:
    hide-uri-scheme: ''
    icons: 'svg'
  extensions:
    - './lib/extensions/gist-block-macro'
    - './lib/extensions/prism-line-highlight-tree-processor'
output:
  dir: ./public
