= Antora packages
:uri-antora-asciidoc-loader: https://gitlab.com/antora/antora/tree/master/packages/asciidoc-loader
:uri-antora-page-composer: https://gitlab.com/antora/antora/tree/master/packages/page-composer

This directory contains custom Antora packages.

asciidoc-loader::
This package is a fork of the default {uri-antora-asciidoc-loader}[AsciiDoc Loader library].
Only the file `load-asciidoc.js` contains changes compared to the upstream project:
+
[source,js,indent=0]
----
include::asciidoc-loader/lib/load-asciidoc.js[tags=override]
----
+
As you can see in the code snippet above, we define a custom converter as an AsciiDoc option in the generator.
[NOTE]
====
`converter` is a function so we are able to pass the callback to the dedicated Antora HTML5 converter.

The `converter` function is defined in `create-converter.js`.
====

fn-page-composer::
This package extends the default {uri-antora-page-composer}[Page composer library] to use _String Literals_ instead of Handlebars.
This implementation provides a `function` for each layout.
The `function` takes one argument, the `uiModel` and returns the page as a _String_.

ui-loader::
We've added support for loading the `ui` from a directory.
See https://gitlab.com/antora/antora/merge_requests/228
